### ISSUE TITLE
Interaction for the map (mouseover per state)

### ISSUE THREAD

**Issue by elissa26** [Erikqtx/Studienarbeit-Gruppe5#11]

**Comment by elissa26** [comment]
Buttons for the map:

115f096d43935a25cbaeb1e5bf3331acff323ba2

**Comment by Erikqtx** [comment]
First Bunch
d68e30b8d6f4e063c55ae25f885f5c5d4730bfb8

**Comment by elissa26** [comment]
Charts for states in 2015
60d4c66f28a825ecac2400364458054ebfe07acc

**Comment by moritzneubauer** [comment]
Charts for States 2016

https://github.com/Erikqtx/Studienarbeit-Gruppe5/commit/2bae3ec94c748c17f74f1a78259d4ae424703773

**Comment by Erikqtx** [comment]
Not going to use a map anylonger.

**Comment by Erikqtx** [comment]
2b0e20528c3c6ecc0c27c6f30be3cfba929a59e2
