### ISSUE TITLE
Adding Summarized Chart(Country)

### ISSUE THREAD

**Issue by Erikqtx** [Erikqtx/Studienarbeit-Gruppe5#15]

**Comment by moritzneubauer** [comment]
Adding Chart 2016 Country

https://github.com/Erikqtx/Studienarbeit-Gruppe5/commit/b06aaab8672e2542529c41564716b5ade87c955f

**Comment by Erikqtx** [comment]
Chart 2015 Country

04a0337773cc1e3ca482407938cf2a200907fc26
