### ISSUE TITLE
Styling Content

### ISSUE THREAD

**Issue by Erikqtx** [Erikqtx/Studienarbeit-Gruppe5#16]

**Comment by moritzneubauer** [comment]
styling the map - first step  0a1139b

**Comment by moritzneubauer** [comment]
style grid 81f6c2c

**Comment by moritzneubauer** [comment]
styling grid for mobile  bd1c942

**Comment by moritzneubauer** [comment]
Styling the Map

https://github.com/Erikqtx/Studienarbeit-Gruppe5/commit/2e55a8ec41a62fdbeb57d17eecc9018de105c96a

**Comment by elissa26** [comment]
cleanup
7026caccf57b2e17414710040a75399d45faf7ad

**Comment by Erikqtx** [comment]
775f2bb13201a9c95f1082bf84f716061c2786d7
