### ISSUE TITLE
Create Tests for Map, CSVToJSON etc.

### ISSUE THREAD

**Issue by Erikqtx** [Erikqtx/Studienarbeit-Gruppe5#19]

**Comment by elissa26** [comment]
Test for Buttons

e0656945fd280010c70b82010d35de0566bac623

**Comment by moritzneubauer** [comment]
Testing Snapshots & Rendering MapChart

Testing Snapshots & Rendering App

https://github.com/Erikqtx/Studienarbeit-Gruppe5/commit/4b5ca2e6256d7ecf59135f7bd4f6cd3b575345c9

**Comment by moritzneubauer** [comment]
Testing Header Rendering + CleanUp

https://github.com/Erikqtx/Studienarbeit-Gruppe5/commit/c48bcd63eb9f82b2dac9abe7cc855c5706d9f50d

**Comment by moritzneubauer** [comment]
Testing App Rendering

b2e2855

**Comment by elissa26** [comment]
Test USAChart2015 und USAChart2016
26039c1512d56ee69a8e6d100ce0b1cbb1b0ae82

**Comment by Erikqtx** [comment]
Test FilterData

04a0337773cc1e3ca482407938cf2a200907fc26

**Comment by Erikqtx** [comment]
b291f1a4bc82c39680a85dce2c0cf952789bae61

**Comment by Erikqtx** [comment]
9f32d525373250d8c4c6be905baa3c27d7cc01e3
