### ISSUE TITLE
csv to json

### ISSUE THREAD

**Issue by Erikqtx** [Erikqtx/Studienarbeit-Gruppe5#7]

**Comment by moritzneubauer** [comment]
first step
https://github.com/Erikqtx/Studienarbeit-Gruppe5/commit/9b5fd1d6e72d82a903641de4089927adea97215f

**Comment by elissa26** [comment]
second step
c1de7c88b336ce4e113527ecc63da55621d38cd0

**Comment by Erikqtx** [comment]
final step
https://github.com/Erikqtx/Studienarbeit-Gruppe5/commit/c1de7c88b336ce4e113527ecc63da55621d38cd0
